#!/usr/bin/env bash

set -e

echo "Usage:"
echo "  help        Display the help message and exit."
echo "  check       Check status of Redis server."
echo "  shell       Launch redis shell."
echo "  flushall    Flush redis cache."